In [2]:
import os
import numpy as np
import polars as pl
import pandas as pd
from plotly import express as px
from datetime import datetime
from dotenv import load_dotenv
from mktools.get_data import load_data_pd

load_dotenv()

True

In [4]:
# %%timeit
panda_df = load_data_pd(
    sheet_name="data",
    sheet_id=os.environ["SHEET_ID"],
    usecols=[
        "UID",
        "SUID",
        "NAME",
        "CHARACTER",
        "MAP",
        "PLACE",
        "PLAYERS",
        "DATE",
        "SEASON",
    ],
)

In [5]:
panda_df

,UID,SUID,NAME,CHARACTER,MAP,PLACE,PLAYERS,DATE,SEASON
0,1,1,Cole,Toad,Sherbet Land,4,4,2021-09-20,0
1,1,1,Connor,Yoshi,Sherbet Land,2,4,2021-09-20,0
2,1,1,Cooper,Peach,Sherbet Land,1,4,2021-09-20,0
3,1,1,Triston,Bowser,Sherbet Land,3,4,2021-09-20,0
4,2,1,Cole,Toad,Kalimari Desert,4,4,2021-09-20,0
...,...,...,...,...,...,...,...,...,...
21606,6279,735,Konnor,Yoshi,Mario Raceway,3,3,2024-07-15,11
21607,6280,735,Cooper,Yoshi,Toad's Turnpike,1,4,2024-07-15,11
21608,6280,735,Regan,Toad,Toad's Turnpike,2,4,2024-07-15,11
21609,6280,735,Connor,Peach,Toad's Turnpike,3,4,2024-07-15,11
21610,6280,735,Konnor,Bowser,Toad's Turnpike,4,4,2024-07-15,11

In [6]:
mdf = panda_df[panda_df["NAME"] == "Matt"]

In [7]:
panda_df[panda_df["NAME"] == "Cooper"]

,UID,SUID,NAME,CHARACTER,MAP,PLACE,PLAYERS,DATE,SEASON
2,1,1,Cooper,Peach,Sherbet Land,1,4,2021-09-20,0
6,2,1,Cooper,Yoshi,Kalimari Desert,1,4,2021-09-20,0
10,3,1,Cooper,Toad,Yoshi Valley,1,4,2021-09-20,0
15,4,1,Cooper,Mario,Wario Stadium,1,4,2021-09-20,0
18,5,1,Cooper,Luigi,Choco Mountain,1,3,2021-09-20,0
...,...,...,...,...,...,...,...,...,...
21588,6273,733,Cooper,Peach,Frappe Snowland,3,4,2024-07-13,11
21590,6274,733,Cooper,D.K.,Wario Stadium,1,4,2024-07-13,11
21602,6278,735,Cooper,Yoshi,Sherbet Land,2,3,2024-07-15,11
21605,6279,735,Cooper,Toad,Mario Raceway,2,3,2024-07-15,11
21607,6280,735,Cooper,Yoshi,Toad's Turnpike,1,4,2024-07-15,11

In [8]:
panda_df["NAME"].str.contains("Cooper").any()

True

In [9]:
panda_df["NAME"].value_counts()

NAME
Blake       4062
Cooper      3500
Connor      2494
Cole        2492
Regan       2371
Matt        1756
Triston      878
Jake         552
Graber       478
Luke         427
Anthony      348
Domingo      329
Colton       328
Robert       252
Chandler     250
Garrett      212
Konnor       148
Miller       111
Sam           86
Ben           84
Randy         76
Joey          51
Caskey        46
Andrew        45
Hughes        37
Chloe         36
Mikey         27
Antonio       23
Martin        19
Austin        18
Kayla         18
Coop W        16
Justin        11
Duncan P      11
Kali           8
Mitch          7
Billy          2
Kieran         2
Name: count, dtype: int64

In [32]:
ct = pd.crosstab(index=panda_df["UID"], columns=panda_df["NAME"]).T.reset_index().rename_axis("", axis="index")

ct

UID,NAME,1,2,3,4,5,6,7,8,9,...,6271,6272,6273,6274,6275,6276,6277,6278,6279,6280
,,,,,,,,,,,,,,,,,,,,,
0,Andrew,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Anthony,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Antonio,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,1,1,0,0,0
3,Austin,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Ben,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,Billy,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,Blake,0,0,0,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
7,Caskey,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,Chandler,0,0,0,0,0,0,0,0,0,...,0,1,0,0,1,1,1,0,0,0
9,Chloe,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,Cole,1,1,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,Colton,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
12,Connor,1,1,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,1
13,Coop W,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,Cooper,1,1,1,1,1,1,1,1,1,...,1,1,1,1,0,0,0,1,1,1
15,Domingo,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,Duncan P,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,Garrett,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,Graber,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,Hughes,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,Jake,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,Joey,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,Justin,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,Kali,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,Kayla,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,Kieran,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,Konnor,0,0,0,0,0,0,0,0,0,...,0,1,1,1,0,0,0,1,1,1
27,Luke,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
28,Martin,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,Matt,0,0,0,0,0,0,1,1,1,...,1,1,1,0,0,0,0,0,0,0
30,Mikey,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,Miller,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32,Mitch,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
33,Randy,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34,Regan,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,1
35,Robert,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
36,Sam,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37,Triston,1,1,1,0,0,0,0,0,0,...,1,0,1,0,0,0,0,0,0,0

In [39]:
ct = pd.crosstab(index=panda_df["UID"], columns=panda_df["NAME"]).reset_index().rename_axis(None, axis="index")

ct

NAME,UID,Andrew,Anthony,Antonio,Austin,Ben,Billy,Blake,Caskey,Chandler,...,Martin,Matt,Mikey,Miller,Mitch,Randy,Regan,Robert,Sam,Triston
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,4,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6275,6276,0,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
6276,6277,0,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
6277,6278,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
6278,6279,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
6279,6280,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [40]:
f = panda_df[panda_df["PLAYERS"] == 4]

f

,UID,SUID,NAME,CHARACTER,MAP,PLACE,PLAYERS,DATE,SEASON
0,1,1,Cole,Toad,Sherbet Land,4,4,2021-09-20,0
1,1,1,Connor,Yoshi,Sherbet Land,2,4,2021-09-20,0
2,1,1,Cooper,Peach,Sherbet Land,1,4,2021-09-20,0
3,1,1,Triston,Bowser,Sherbet Land,3,4,2021-09-20,0
4,2,1,Cole,Toad,Kalimari Desert,4,4,2021-09-20,0
...,...,...,...,...,...,...,...,...,...
21593,6274,733,Luke,Peach,Wario Stadium,4,4,2024-07-13,11
21607,6280,735,Cooper,Yoshi,Toad's Turnpike,1,4,2024-07-15,11
21608,6280,735,Regan,Toad,Toad's Turnpike,2,4,2024-07-15,11
21609,6280,735,Connor,Peach,Toad's Turnpike,3,4,2024-07-15,11
21610,6280,735,Konnor,Bowser,Toad's Turnpike,4,4,2024-07-15,11

In [45]:
f["NAME"].unique()

array(['Cole', 'Connor', 'Cooper', 'Triston', 'Blake', 'Matt', 'Regan',
       'Jake', 'Chandler', 'Luke', 'Caskey', 'Duncan P', 'Graber',
       'Anthony', 'Garrett', 'Konnor', 'Joey', 'Martin', 'Andrew',
       'Miller', 'Kayla', 'Chloe', 'Ben', 'Sam', 'Robert', 'Colton',
       'Mitch', 'Justin', 'Coop W', 'Randy', 'Domingo', 'Austin', 'Billy',
       'Mikey', 'Hughes', 'Kieran', 'Kali', 'Antonio'], dtype=object)

In [49]:
played_names = []
played_dfs = []

for name in f["NAME"].unique():

    tdf = f[f["NAME"] == name]

    played_dfs.append(tdf)
    played_names.append(name)

played = dict(zip(played_names, played_dfs))

played

{'Cole':         UID  SUID  NAME CHARACTER              MAP  PLACE  PLAYERS  \
 0         1     1  Cole      Toad     Sherbet Land      4        4
 4         2     1  Cole      Toad  Kalimari Desert      4        4
 8         3     1  Cole     Yoshi     Yoshi Valley      4        4
 13        4     1  Cole      Toad    Wario Stadium      2        4
 20        6     1  Cole     Peach  Bowser's Castle      2        4
 ...     ...   ...   ...       ...              ...    ...      ...
 20890  6059   715  Cole     Peach  Frappe Snowland      2        4
 20899  6061   715  Cole     Peach  Bowser's Castle      3        4
 20907  6063   715  Cole      Toad     Yoshi Valley      3        4
 20910  6064   715  Cole      Toad  Kalimari Desert      2        4
 21402  6213   729  Cole      Toad    Wario Stadium      4        4

              DATE  SEASON
 0      2021-09-20       0
 4      2021-09-20       0
 8      2021-09-20       0
 13     2021-09-20       0
 20     2021-09-20       0
 ...           ...     ...
 20890  2024-06-25      11
 20899  2024-06-25      11
 20907  2024-06-25      11
 20910  2024-06-25      11
 21402  2024-07-09      11

 [1520 rows x 9 columns],
 'Connor':         UID  SUID    NAME CHARACTER                MAP  PLACE  PLAYERS  \
 1         1     1  Connor     Yoshi       Sherbet Land      2        4
 5         2     1  Connor     Peach    Kalimari Desert      2        4
 9         3     1  Connor     Peach       Yoshi Valley      2        4
 14        4     1  Connor     Yoshi      Wario Stadium      4        4
 21        6     1  Connor      Toad    Bowser's Castle      1        4
 ...     ...   ...     ...       ...                ...    ...      ...
 20880  6056   715  Connor    Bowser  Banshee Boardwalk      4        4
 20903  6062   715  Connor     Peach      Royal Raceway      3        4
 21400  6213   729  Connor     Yoshi      Wario Stadium      2        4
 21468  6235   731  Connor     Yoshi       Yoshi Valley      2        4
 21609  6280   735  Connor     Peach    Toad's Turnpike      3        4

              DATE  SEASON
 1      2021-09-20       0
 5      2021-09-20       0
 9      2021-09-20       0
 14     2021-09-20       0
 21     2021-09-20       0
 ...           ...     ...
 20880  2024-06-25      11
 20903  2024-06-25      11
 21400  2024-07-09      11
 21468  2024-07-11      11
 21609  2024-07-15      11

 [1539 rows x 9 columns],
 'Cooper':         UID  SUID    NAME CHARACTER              MAP  PLACE  PLAYERS  \
 2         1     1  Cooper     Peach     Sherbet Land      1        4
 6         2     1  Cooper     Yoshi  Kalimari Desert      1        4
 10        3     1  Cooper      Toad     Yoshi Valley      1        4
 15        4     1  Cooper     Mario    Wario Stadium      1        4
 22        6     1  Cooper    Bowser  Bowser's Castle      3        4
 ...     ...   ...     ...       ...              ...    ...      ...
 21575  6270   733  Cooper     Luigi  Bowser's Castle      1        4
 21582  6272   733  Cooper     Wario    Wario Stadium      1        4
 21588  6273   733  Cooper     Peach  Frappe Snowland      3        4
 21590  6274   733  Cooper      D.K.    Wario Stadium      1        4
 21607  6280   735  Cooper     Yoshi  Toad's Turnpike      1        4

              DATE  SEASON
 2      2021-09-20       0
 6      2021-09-20       0
 10     2021-09-20       0
 15     2021-09-20       0
 22     2021-09-20       0
 ...           ...     ...
 21575  2024-07-13      11
 21582  2024-07-13      11
 21588  2024-07-13      11
 21590  2024-07-13      11
 21607  2024-07-15      11

 [2065 rows x 9 columns],
 'Triston':         UID  SUID     NAME CHARACTER                MAP  PLACE  PLAYERS  \
 3         1     1  Triston    Bowser       Sherbet Land      3        4
 7         2     1  Triston    Bowser    Kalimari Desert      3        4
 11        3     1  Triston    Bowser       Yoshi Valley      3        4
 45       13     2  Triston     Yoshi      Mario Raceway      4        4
 53       15     2  Triston    Bowser  Banshee Boardwalk      4        4
 ...     ...   ...      ...       ...                ...    ...      ...
 21514  6248   732  Triston     Yoshi      Mario Raceway      4        4
 21515  6249   732  Triston     Yoshi     Choco Mountain      1        4
 21522  6250   732  Triston     Yoshi      Wario Stadium      4        4
 21578  6270   733  Triston      Toad    Bowser's Castle      4        4
 21589  6273   733  Triston      Toad    Frappe Snowland      4        4

              DATE  SEASON
 3      2021-09-20       0
 7      2021-09-20       0
 11     2021-09-20       0
 45     2021-09-21       0
 53     2021-09-21       0
 ...           ...     ...
 21514  2024-07-12      11
 21515  2024-07-12      11
 21522  2024-07-12      11
 21578  2024-07-13      11
 21589  2024-07-13      11

 [558 rows x 9 columns],
 'Blake':         UID  SUID   NAME CHARACTER                MAP  PLACE  PLAYERS  \
 12        4     1  Blake     Peach      Wario Stadium      3        4
 19        6     1  Blake     Yoshi    Bowser's Castle      4        4
 23        7     1  Blake     Yoshi  Banshee Boardwalk      1        4
 46       14     2  Blake     Yoshi      Mario Raceway      4        4
 54       16     2  Blake     Yoshi      Wario Stadium      3        4
 ...     ...   ...    ...       ...                ...    ...      ...
 20892  6059   715  Blake     Yoshi    Frappe Snowland      4        4
 20898  6061   715  Blake      Toad    Bowser's Castle      2        4
 20905  6063   715  Blake     Yoshi       Yoshi Valley      1        4
 20911  6064   715  Blake     Yoshi    Kalimari Desert      3        4
 21401  6213   729  Blake     Peach      Wario Stadium      3        4

              DATE  SEASON
 12     2021-09-20       0
 19     2021-09-20       0
 23     2021-09-20       0
 46     2021-09-21       0
 54     2021-09-21       0
 ...           ...     ...
 20892  2024-06-25      11
 20898  2024-06-25      11
 20905  2024-06-25      11
 20911  2024-06-25      11
 21401  2024-07-09      11

 [2315 rows x 9 columns],
 'Matt':         UID  SUID  NAME CHARACTER                 MAP  PLACE  PLAYERS  \
 26        7     1  Matt     Peach   Banshee Boardwalk      2        4
 99       27     3  Matt      Toad  Koopa Troopa Beach      2        4
 103      28     3  Matt      Toad       Royal Raceway      1        4
 106      29     3  Matt     Yoshi       D.K.'s Jungle      2        4
 149      41     4  Matt     Yoshi     Bowser's Castle      3        4
 ...     ...   ...   ...       ...                 ...    ...      ...
 21513  6248   732  Matt      Toad       Mario Raceway      3        4
 21564  6265   733  Matt     Luigi  Koopa Troopa Beach      4        4
 21577  6270   733  Matt     Yoshi     Bowser's Castle      3        4
 21583  6272   733  Matt    Bowser       Wario Stadium      2        4
 21587  6273   733  Matt    Bowser     Frappe Snowland      2        4

              DATE  SEASON
 26     2021-09-20       0
 99     2021-09-22       0
 103    2021-09-22       0
 106    2021-09-22       0
 149    2021-09-23       0
 ...           ...     ...
 21513  2024-07-12      11
 21564  2024-07-13      11
 21577  2024-07-13      11
 21583  2024-07-13      11
 21587  2024-07-13      11

 [1183 rows x 9 columns],
 'Regan':         UID  SUID   NAME CHARACTER                MAP  PLACE  PLAYERS  \
 44       13     2  Regan    Bowser      Mario Raceway      3        4
 52       15     2  Regan      Toad  Banshee Boardwalk      3        4
 60       17     2  Regan     Peach      Royal Raceway      3        4
 65       18     2  Regan      Toad    Toad's Turnpike      2        4
 68       19     2  Regan      Toad    Bowser's Castle      3        4
 ...     ...   ...    ...       ...                ...    ...      ...
 21516  6249   732  Regan      Toad     Choco Mountain      2        4
 21521  6250   732  Regan      Toad      Wario Stadium      3        4
 21530  6253   732  Regan     Yoshi    Toad's Turnpike      2        4
 21533  6254   732  Regan     Yoshi    Bowser's Castle      1        4
 21608  6280   735  Regan      Toad    Toad's Turnpike      2        4

              DATE  SEASON
 44     2021-09-21       0
 52     2021-09-21       0
 60     2021-09-21       0
 65     2021-09-21       0
 68     2021-09-21       0
 ...           ...     ...
 21516  2024-07-12      11
 21521  2024-07-12      11
 21530  2024-07-12      11
 21533  2024-07-12      11
 21608  2024-07-15      11

 [1464 rows x 9 columns],
 'Jake':         UID  SUID  NAME CHARACTER                 MAP  PLACE  PLAYERS  \
 49       14     2  Jake    Bowser        Sherbet Land      3        4
 57       16     2  Jake    Bowser       Wario Stadium      4        4
 64       18     2  Jake    Bowser     Toad's Turnpike      4        4
 73       20     2  Jake    Bowser       D.K.'s Jungle      4        4
 75       21     2  Jake    Bowser        Yoshi Valley      4        4
 ...     ...   ...   ...       ...                 ...    ...      ...
 21102  6120   719  Jake    Bowser  Koopa Troopa Beach      3        4
 21106  6121   719  Jake     Peach  Koopa Troopa Beach      3        4
 21110  6122   719  Jake      Toad     Frappe Snowland      3        4
 21114  6123   719  Jake     Peach       Wario Stadium      3        4
 21118  6124   719  Jake     Peach       Royal Raceway      3        4

              DATE  SEASON
 49     2021-09-21       0
 57     2021-09-21       0
 64     2021-09-21       0
 73     2021-09-21       0
 75     2021-09-21       0
 ...           ...     ...
 21102  2024-06-29      11
 21106  2024-06-29      11
 21110  2024-06-29      11
 21114  2024-06-29      11
 21118  2024-06-29      11

 [392 rows x 9 columns],
 'Chandler':         UID  SUID      NAME CHARACTER                 MAP  PLACE  PLAYERS  \
 180      50     5  Chandler    Bowser       Wario Stadium      4        4
 187      52     5  Chandler     Peach        Yoshi Valley      4        4
 191      53     5  Chandler    Bowser       D.K.'s Jungle      4        4
 423     117    12  Chandler     Peach     Toad's Turnpike      1        4
 427     118    12  Chandler     Yoshi        Yoshi Valley      2        4
 ...     ...   ...       ...       ...                 ...    ...      ...
 21504  6246   732  Chandler     Yoshi   Banshee Boardwalk      2        4
 21509  6247   732  Chandler     Yoshi       Royal Raceway      3        4
 21562  6265   733  Chandler     Yoshi  Koopa Troopa Beach      2        4
 21576  6270   733  Chandler     Peach     Bowser's Castle      2        4
 21584  6272   733  Chandler     Yoshi       Wario Stadium      3        4

              DATE  SEASON
 180    2021-09-24       0
 187    2021-09-24       0
 191    2021-09-24       0
 423    2021-10-01       0
 427    2021-10-01       0
 ...           ...     ...
 21504  2024-07-12      11
 21509  2024-07-12      11
 21562  2024-07-13      11
 21576  2024-07-13      11
 21584  2024-07-13      11

 [154 rows x 9 columns],
 'Luke':         UID  SUID  NAME CHARACTER              MAP  PLACE  PLAYERS  \
 182      50     5  Luke     Yoshi    Wario Stadium      3        4
 189      52     5  Luke      Toad     Yoshi Valley      3        4
 651     183    17  Luke      Toad     Sherbet Land      1        4
 658     185    17  Luke     Yoshi     Yoshi Valley      3        4
 665     187    17  Luke     Yoshi    D.K.'s Jungle      1        4
 ...     ...   ...   ...       ...              ...    ...      ...
 21442  6227   730  Luke     Peach    Wario Stadium      2        4
 21458  6231   731  Luke      Toad    Royal Raceway      4        4
 21529  6253   732  Luke      Toad  Toad's Turnpike      1        4
 21534  6254   732  Luke     Peach  Bowser's Castle      2        4
 21593  6274   733  Luke     Peach    Wario Stadium      4        4

              DATE  SEASON
 182    2021-09-24       0
 189    2021-09-24       0
 651    2021-10-04       0
 658    2021-10-04       0
 665    2021-10-04       0
 ...           ...     ...
 21442  2024-07-10      11
 21458  2024-07-11      11
 21529  2024-07-12      11
 21534  2024-07-12      11
 21593  2024-07-13      11

 [314 rows x 9 columns],
 'Caskey':         UID  SUID    NAME CHARACTER                 MAP  PLACE  PLAYERS  \
 196      54     5  Caskey     Peach       Royal Raceway      3        4
 199      55     5  Caskey     Yoshi  Koopa Troopa Beach      4        4
 1344    379    31  Caskey    Bowser       Royal Raceway      4        4
 1349    380    31  Caskey     Yoshi     Toad's Turnpike      4        4
 1353    381    31  Caskey     Peach        Yoshi Valley      4        4
 1357    382    31  Caskey     Peach       D.K.'s Jungle      3        4
 1422    400    33  Caskey    Bowser       Wario Stadium      4        4
 1426    401    33  Caskey     Yoshi     Bowser's Castle      4        4
 1430    402    33  Caskey     Peach   Banshee Boardwalk      4        4
 2658    763    62  Caskey    Bowser       Wario Stadium      4        4
 2661    764    62  Caskey    Bowser     Toad's Turnpike      3        4
 4661   1238   166  Caskey     Peach        Yoshi Valley      4        4
 4665   1239   166  Caskey     Peach       Wario Stadium      4        4
 5262   1421   188  Caskey     Luigi  Koopa Troopa Beach      4        4
 5266   1422   188  Caskey     Peach       Wario Stadium      4        4
 5268   1423   188  Caskey     Peach     Toad's Turnpike      2        4
 5273   1424   188  Caskey     Peach       D.K.'s Jungle      3        4
 5497   1497   194  Caskey      Toad     Toad's Turnpike      4        4
 7109   1984   248  Caskey    Bowser       D.K.'s Jungle      4        4
 7113   1985   248  Caskey      Toad       Wario Stadium      4        4
 7120   1987   248  Caskey     Mario       Royal Raceway      3        4
 8129   2296   279  Caskey     Wario  Koopa Troopa Beach      4        4
 10861  3147   360  Caskey     Yoshi       D.K.'s Jungle      2        4
 10865  3148   360  Caskey     Yoshi       Royal Raceway      2        4
 11031  3197   364  Caskey      Toad        Sherbet Land      4        4
 11035  3198   364  Caskey      Toad     Toad's Turnpike      4        4
 11040  3200   364  Caskey     Peach       Wario Stadium      1        4
 11047  3201   364  Caskey     Yoshi       Royal Raceway      4        4
 11127  3223   365  Caskey     Luigi       Royal Raceway      3        4
 13489  3913   431  Caskey     Luigi       Royal Raceway      4        4
 13499  3916   431  Caskey     Luigi       Wario Stadium      2        4
 15327  4495   490  Caskey     Yoshi       Wario Stadium      2        4
 16248  4767   532  Caskey     Yoshi       Wario Stadium      4        4
 16256  4769   532  Caskey     Peach       Royal Raceway      4        4
 18276  5345   638  Caskey    Bowser     Bowser's Castle      4        4
 18280  5346   638  Caskey    Bowser       Royal Raceway      4        4
 19713  5744   691  Caskey      Toad        Moo Moo Farm      3        4
 19719  5746   691  Caskey     Peach       Royal Raceway      2        4
 19726  5748   691  Caskey      Toad       Wario Stadium      2        4

              DATE  SEASON
 196    2021-09-24       0
 199    2021-09-24       0
 1344   2021-10-16       0
 1349   2021-10-16       0
 1353   2021-10-16       0
 1357   2021-10-16       0
 1422   2021-10-17       0
 1426   2021-10-18       0
 1430   2021-10-18       0
 2658   2021-11-14       1
 2661   2021-11-14       1
 4661   2022-01-23       1
 4665   2022-01-23       1
 5262   2022-02-13       2
 5266   2022-02-13       2
 5268   2022-02-13       2
 5273   2022-02-13       2
 5497   2022-02-18       2
 7109   2022-04-07       3
 7113   2022-04-07       3
 7120   2022-04-07       3
 8129   2022-05-07       3
 10861  2022-08-05       5
 10865  2022-08-05       5
 11031  2022-08-11       5
 11035  2022-08-11       5
 11040  2022-08-11       5
 11047  2022-08-11       5
 11127  2022-08-12       5
 13489  2022-10-16       6
 13499  2022-10-16       6
 15327  2022-12-29       7
 16248  2023-02-12       8
 16256  2023-02-12       8
 18276  2023-06-14       9
 18280  2023-06-14       9
 19713  2024-06-01      10
 19719  2024-06-01      10
 19726  2024-06-01      10  ,
 'Duncan P':        UID  SUID      NAME CHARACTER                 MAP  PLACE  PLAYERS  \
 205     56     6  Duncan P     Luigi     Kalimari Desert      4        4
 209     57     6  Duncan P     Luigi   Banshee Boardwalk      4        4
 3525  1004    88  Duncan P     Luigi        Yoshi Valley      4        4
 3529  1005    88  Duncan P     Peach       Wario Stadium      4        4
 3533  1006    88  Duncan P     Peach        Sherbet Land      4        4
 3536  1007    88  Duncan P     Peach       Mario Raceway      3        4
 3541  1008    88  Duncan P     Peach  Koopa Troopa Beach      4        4
 3544  1009    88  Duncan P     Luigi     Frappe Snowland      3        4
 6091  1675   208  Duncan P     Peach  Koopa Troopa Beach      4        4

             DATE  SEASON
 205   2021-09-24       0
 209   2021-09-24       0
 3525  2021-12-07       1
 3529  2021-12-07       1
 3533  2021-12-07       1
 3536  2021-12-07       1
 3541  2021-12-07       1
 3544  2021-12-07       1
 6091  2022-03-04       2  ,
 'Graber':         UID  SUID    NAME CHARACTER                 MAP  PLACE  PLAYERS  \
 206      56     6  Graber      Toad     Kalimari Desert      3        4
 210      57     6  Graber      Toad   Banshee Boardwalk      2        4
 213      58     6  Graber      Toad     Bowser's Castle      1        4
 245      67     8  Graber     Peach     Toad's Turnpike      4        4
 250      68     8  Graber     Peach       Royal Raceway      4        4
 ...     ...   ...     ...       ...                 ...    ...      ...
 19838  5776   691  Graber      Toad       Royal Raceway      4        4
 20006  5821   696  Graber     Peach  Koopa Troopa Beach      4        4
 20053  5833   697  Graber     Peach   Banshee Boardwalk      2        4
 20058  5834   697  Graber     Peach        Yoshi Valley      3        4
 20062  5835   697  Graber     Peach       D.K.'s Jungle      3        4

              DATE  SEASON
 206    2021-09-24       0
 210    2021-09-24       0
 213    2021-09-24       0
 245    2021-09-27       0
 250    2021-09-27       0
 ...           ...     ...
 19838  2024-06-01      10
 20006  2024-06-06      10
 20053  2024-06-07      10
 20058  2024-06-07      10
 20062  2024-06-07      10

 [319 rows x 9 columns],
 'Anthony':         UID  SUID     NAME CHARACTER              MAP  PLACE  PLAYERS  \
 410     113    11  Anthony    Bowser     Yoshi Valley      4        4
 753     211    19  Anthony     Yoshi  Toad's Turnpike      4        4
 853     239    21  Anthony      Toad  Kalimari Desert      4        4
 1259    352    28  Anthony     Peach  Kalimari Desert      3        4
 1264    353    28  Anthony     Peach    Wario Stadium      4        4
 ...     ...   ...      ...       ...              ...    ...      ...
 18051  5282   627  Anthony      Toad    D.K.'s Jungle      3        4
 18056  5283   627  Anthony     Yoshi    Wario Stadium      4        4
 18060  5284   627  Anthony     Peach  Toad's Turnpike      4        4
 18067  5286   627  Anthony      Toad    Wario Stadium      3        4
 18071  5287   627  Anthony      Toad    Wario Stadium      3        4

              DATE  SEASON
 410    2021-09-30       0
 753    2021-10-05       0
 853    2021-10-07       0
 1259   2021-10-14       0
 1264   2021-10-14       0
 ...           ...     ...
 18051  2023-05-28       9
 18056  2023-05-28       9
 18060  2023-05-28       9
 18067  2023-05-28       9
 18071  2023-05-28       9

 [282 rows x 9 columns],
 'Garrett':         UID  SUID     NAME CHARACTER                MAP  PLACE  PLAYERS  \
 627     176    15  Garrett      Toad    Kalimari Desert      4        4
 631     177    15  Garrett      Toad      D.K.'s Jungle      4        4
 18655  5458   665  Garrett     Luigi    Toad's Turnpike      4        4

In [50]:
first_names = []
first_dfs = []

for name in f["NAME"].unique():

    tdf = f[f["NAME"] == name]

    first_dfs.append(tdf)
    first_names.append(name)

first = dict(zip(first_names, first_dfs))

first

{'Cole':         UID  SUID  NAME CHARACTER              MAP  PLACE  PLAYERS  \
 0         1     1  Cole      Toad     Sherbet Land      4        4
 4         2     1  Cole      Toad  Kalimari Desert      4        4
 8         3     1  Cole     Yoshi     Yoshi Valley      4        4
 13        4     1  Cole      Toad    Wario Stadium      2        4
 20        6     1  Cole     Peach  Bowser's Castle      2        4
 ...     ...   ...   ...       ...              ...    ...      ...
 20890  6059   715  Cole     Peach  Frappe Snowland      2        4
 20899  6061   715  Cole     Peach  Bowser's Castle      3        4
 20907  6063   715  Cole      Toad     Yoshi Valley      3        4
 20910  6064   715  Cole      Toad  Kalimari Desert      2        4
 21402  6213   729  Cole      Toad    Wario Stadium      4        4

              DATE  SEASON
 0      2021-09-20       0
 4      2021-09-20       0
 8      2021-09-20       0
 13     2021-09-20       0
 20     2021-09-20       0
 ...           ...     ...
 20890  2024-06-25      11
 20899  2024-06-25      11
 20907  2024-06-25      11
 20910  2024-06-25      11
 21402  2024-07-09      11

 [1520 rows x 9 columns],
 'Connor':         UID  SUID    NAME CHARACTER                MAP  PLACE  PLAYERS  \
 1         1     1  Connor     Yoshi       Sherbet Land      2        4
 5         2     1  Connor     Peach    Kalimari Desert      2        4
 9         3     1  Connor     Peach       Yoshi Valley      2        4
 14        4     1  Connor     Yoshi      Wario Stadium      4        4
 21        6     1  Connor      Toad    Bowser's Castle      1        4
 ...     ...   ...     ...       ...                ...    ...      ...
 20880  6056   715  Connor    Bowser  Banshee Boardwalk      4        4
 20903  6062   715  Connor     Peach      Royal Raceway      3        4
 21400  6213   729  Connor     Yoshi      Wario Stadium      2        4
 21468  6235   731  Connor     Yoshi       Yoshi Valley      2        4
 21609  6280   735  Connor     Peach    Toad's Turnpike      3        4

              DATE  SEASON
 1      2021-09-20       0
 5      2021-09-20       0
 9      2021-09-20       0
 14     2021-09-20       0
 21     2021-09-20       0
 ...           ...     ...
 20880  2024-06-25      11
 20903  2024-06-25      11
 21400  2024-07-09      11
 21468  2024-07-11      11
 21609  2024-07-15      11

 [1539 rows x 9 columns],
 'Cooper':         UID  SUID    NAME CHARACTER              MAP  PLACE  PLAYERS  \
 2         1     1  Cooper     Peach     Sherbet Land      1        4
 6         2     1  Cooper     Yoshi  Kalimari Desert      1        4
 10        3     1  Cooper      Toad     Yoshi Valley      1        4
 15        4     1  Cooper     Mario    Wario Stadium      1        4
 22        6     1  Cooper    Bowser  Bowser's Castle      3        4
 ...     ...   ...     ...       ...              ...    ...      ...
 21575  6270   733  Cooper     Luigi  Bowser's Castle      1        4
 21582  6272   733  Cooper     Wario    Wario Stadium      1        4
 21588  6273   733  Cooper     Peach  Frappe Snowland      3        4
 21590  6274   733  Cooper      D.K.    Wario Stadium      1        4
 21607  6280   735  Cooper     Yoshi  Toad's Turnpike      1        4

              DATE  SEASON
 2      2021-09-20       0
 6      2021-09-20       0
 10     2021-09-20       0
 15     2021-09-20       0
 22     2021-09-20       0
 ...           ...     ...
 21575  2024-07-13      11
 21582  2024-07-13      11
 21588  2024-07-13      11
 21590  2024-07-13      11
 21607  2024-07-15      11

 [2065 rows x 9 columns],
 'Triston':         UID  SUID     NAME CHARACTER                MAP  PLACE  PLAYERS  \
 3         1     1  Triston    Bowser       Sherbet Land      3        4
 7         2     1  Triston    Bowser    Kalimari Desert      3        4
 11        3     1  Triston    Bowser       Yoshi Valley      3        4
 45       13     2  Triston     Yoshi      Mario Raceway      4        4
 53       15     2  Triston    Bowser  Banshee Boardwalk      4        4
 ...     ...   ...      ...       ...                ...    ...      ...
 21514  6248   732  Triston     Yoshi      Mario Raceway      4        4
 21515  6249   732  Triston     Yoshi     Choco Mountain      1        4
 21522  6250   732  Triston     Yoshi      Wario Stadium      4        4
 21578  6270   733  Triston      Toad    Bowser's Castle      4        4
 21589  6273   733  Triston      Toad    Frappe Snowland      4        4

              DATE  SEASON
 3      2021-09-20       0
 7      2021-09-20       0
 11     2021-09-20       0
 45     2021-09-21       0
 53     2021-09-21       0
 ...           ...     ...
 21514  2024-07-12      11
 21515  2024-07-12      11
 21522  2024-07-12      11
 21578  2024-07-13      11
 21589  2024-07-13      11

 [558 rows x 9 columns],
 'Blake':         UID  SUID   NAME CHARACTER                MAP  PLACE  PLAYERS  \
 12        4     1  Blake     Peach      Wario Stadium      3        4
 19        6     1  Blake     Yoshi    Bowser's Castle      4        4
 23        7     1  Blake     Yoshi  Banshee Boardwalk      1        4
 46       14     2  Blake     Yoshi      Mario Raceway      4        4
 54       16     2  Blake     Yoshi      Wario Stadium      3        4
 ...     ...   ...    ...       ...                ...    ...      ...
 20892  6059   715  Blake     Yoshi    Frappe Snowland      4        4
 20898  6061   715  Blake      Toad    Bowser's Castle      2        4
 20905  6063   715  Blake     Yoshi       Yoshi Valley      1        4
 20911  6064   715  Blake     Yoshi    Kalimari Desert      3        4
 21401  6213   729  Blake     Peach      Wario Stadium      3        4

              DATE  SEASON
 12     2021-09-20       0
 19     2021-09-20       0
 23     2021-09-20       0
 46     2021-09-21       0
 54     2021-09-21       0
 ...           ...     ...
 20892  2024-06-25      11
 20898  2024-06-25      11
 20905  2024-06-25      11
 20911  2024-06-25      11
 21401  2024-07-09      11

 [2315 rows x 9 columns],
 'Matt':         UID  SUID  NAME CHARACTER                 MAP  PLACE  PLAYERS  \
 26        7     1  Matt     Peach   Banshee Boardwalk      2        4
 99       27     3  Matt      Toad  Koopa Troopa Beach      2        4
 103      28     3  Matt      Toad       Royal Raceway      1        4
 106      29     3  Matt     Yoshi       D.K.'s Jungle      2        4
 149      41     4  Matt     Yoshi     Bowser's Castle      3        4
 ...     ...   ...   ...       ...                 ...    ...      ...
 21513  6248   732  Matt      Toad       Mario Raceway      3        4
 21564  6265   733  Matt     Luigi  Koopa Troopa Beach      4        4
 21577  6270   733  Matt     Yoshi     Bowser's Castle      3        4
 21583  6272   733  Matt    Bowser       Wario Stadium      2        4
 21587  6273   733  Matt    Bowser     Frappe Snowland      2        4

              DATE  SEASON
 26     2021-09-20       0
 99     2021-09-22       0
 103    2021-09-22       0
 106    2021-09-22       0
 149    2021-09-23       0
 ...           ...     ...
 21513  2024-07-12      11
 21564  2024-07-13      11
 21577  2024-07-13      11
 21583  2024-07-13      11
 21587  2024-07-13      11

 [1183 rows x 9 columns],
 'Regan':         UID  SUID   NAME CHARACTER                MAP  PLACE  PLAYERS  \
 44       13     2  Regan    Bowser      Mario Raceway      3        4
 52       15     2  Regan      Toad  Banshee Boardwalk      3        4
 60       17     2  Regan     Peach      Royal Raceway      3        4
 65       18     2  Regan      Toad    Toad's Turnpike      2        4
 68       19     2  Regan      Toad    Bowser's Castle      3        4
 ...     ...   ...    ...       ...                ...    ...      ...
 21516  6249   732  Regan      Toad     Choco Mountain      2        4
 21521  6250   732  Regan      Toad      Wario Stadium      3        4
 21530  6253   732  Regan     Yoshi    Toad's Turnpike      2        4
 21533  6254   732  Regan     Yoshi    Bowser's Castle      1        4
 21608  6280   735  Regan      Toad    Toad's Turnpike      2        4

              DATE  SEASON
 44     2021-09-21       0
 52     2021-09-21       0
 60     2021-09-21       0
 65     2021-09-21       0
 68     2021-09-21       0
 ...           ...     ...
 21516  2024-07-12      11
 21521  2024-07-12      11
 21530  2024-07-12      11
 21533  2024-07-12      11
 21608  2024-07-15      11

 [1464 rows x 9 columns],
 'Jake':         UID  SUID  NAME CHARACTER                 MAP  PLACE  PLAYERS  \
 49       14     2  Jake    Bowser        Sherbet Land      3        4
 57       16     2  Jake    Bowser       Wario Stadium      4        4
 64       18     2  Jake    Bowser     Toad's Turnpike      4        4
 73       20     2  Jake    Bowser       D.K.'s Jungle      4        4
 75       21     2  Jake    Bowser        Yoshi Valley      4        4
 ...     ...   ...   ...       ...                 ...    ...      ...
 21102  6120   719  Jake    Bowser  Koopa Troopa Beach      3        4
 21106  6121   719  Jake     Peach  Koopa Troopa Beach      3        4
 21110  6122   719  Jake      Toad     Frappe Snowland      3        4
 21114  6123   719  Jake     Peach       Wario Stadium      3        4
 21118  6124   719  Jake     Peach       Royal Raceway      3        4

              DATE  SEASON
 49     2021-09-21       0
 57     2021-09-21       0
 64     2021-09-21       0
 73     2021-09-21       0
 75     2021-09-21       0
 ...           ...     ...
 21102  2024-06-29      11
 21106  2024-06-29      11
 21110  2024-06-29      11
 21114  2024-06-29      11
 21118  2024-06-29      11

 [392 rows x 9 columns],
 'Chandler':         UID  SUID      NAME CHARACTER                 MAP  PLACE  PLAYERS  \
 180      50     5  Chandler    Bowser       Wario Stadium      4        4
 187      52     5  Chandler     Peach        Yoshi Valley      4        4
 191      53     5  Chandler    Bowser       D.K.'s Jungle      4        4
 423     117    12  Chandler     Peach     Toad's Turnpike      1        4
 427     118    12  Chandler     Yoshi        Yoshi Valley      2        4
 ...     ...   ...       ...       ...                 ...    ...      ...
 21504  6246   732  Chandler     Yoshi   Banshee Boardwalk      2        4
 21509  6247   732  Chandler     Yoshi       Royal Raceway      3        4
 21562  6265   733  Chandler     Yoshi  Koopa Troopa Beach      2        4
 21576  6270   733  Chandler     Peach     Bowser's Castle      2        4
 21584  6272   733  Chandler     Yoshi       Wario Stadium      3        4

              DATE  SEASON
 180    2021-09-24       0
 187    2021-09-24       0
 191    2021-09-24       0
 423    2021-10-01       0
 427    2021-10-01       0
 ...           ...     ...
 21504  2024-07-12      11
 21509  2024-07-12      11
 21562  2024-07-13      11
 21576  2024-07-13      11
 21584  2024-07-13      11

 [154 rows x 9 columns],
 'Luke':         UID  SUID  NAME CHARACTER              MAP  PLACE  PLAYERS  \
 182      50     5  Luke     Yoshi    Wario Stadium      3        4
 189      52     5  Luke      Toad     Yoshi Valley      3        4
 651     183    17  Luke      Toad     Sherbet Land      1        4
 658     185    17  Luke     Yoshi     Yoshi Valley      3        4
 665     187    17  Luke     Yoshi    D.K.'s Jungle      1        4
 ...     ...   ...   ...       ...              ...    ...      ...
 21442  6227   730  Luke     Peach    Wario Stadium      2        4
 21458  6231   731  Luke      Toad    Royal Raceway      4        4
 21529  6253   732  Luke      Toad  Toad's Turnpike      1        4
 21534  6254   732  Luke     Peach  Bowser's Castle      2        4
 21593  6274   733  Luke     Peach    Wario Stadium      4        4

              DATE  SEASON
 182    2021-09-24       0
 189    2021-09-24       0
 651    2021-10-04       0
 658    2021-10-04       0
 665    2021-10-04       0
 ...           ...     ...
 21442  2024-07-10      11
 21458  2024-07-11      11
 21529  2024-07-12      11
 21534  2024-07-12      11
 21593  2024-07-13      11

 [314 rows x 9 columns],
 'Caskey':         UID  SUID    NAME CHARACTER                 MAP  PLACE  PLAYERS  \
 196      54     5  Caskey     Peach       Royal Raceway      3        4
 199      55     5  Caskey     Yoshi  Koopa Troopa Beach      4        4
 1344    379    31  Caskey    Bowser       Royal Raceway      4        4
 1349    380    31  Caskey     Yoshi     Toad's Turnpike      4        4
 1353    381    31  Caskey     Peach        Yoshi Valley      4        4
 1357    382    31  Caskey     Peach       D.K.'s Jungle      3        4
 1422    400    33  Caskey    Bowser       Wario Stadium      4        4
 1426    401    33  Caskey     Yoshi     Bowser's Castle      4        4
 1430    402    33  Caskey     Peach   Banshee Boardwalk      4        4
 2658    763    62  Caskey    Bowser       Wario Stadium      4        4
 2661    764    62  Caskey    Bowser     Toad's Turnpike      3        4
 4661   1238   166  Caskey     Peach        Yoshi Valley      4        4
 4665   1239   166  Caskey     Peach       Wario Stadium      4        4
 5262   1421   188  Caskey     Luigi  Koopa Troopa Beach      4        4
 5266   1422   188  Caskey     Peach       Wario Stadium      4        4
 5268   1423   188  Caskey     Peach     Toad's Turnpike      2        4
 5273   1424   188  Caskey     Peach       D.K.'s Jungle      3        4
 5497   1497   194  Caskey      Toad     Toad's Turnpike      4        4
 7109   1984   248  Caskey    Bowser       D.K.'s Jungle      4        4
 7113   1985   248  Caskey      Toad       Wario Stadium      4        4
 7120   1987   248  Caskey     Mario       Royal Raceway      3        4
 8129   2296   279  Caskey     Wario  Koopa Troopa Beach      4        4
 10861  3147   360  Caskey     Yoshi       D.K.'s Jungle      2        4
 10865  3148   360  Caskey     Yoshi       Royal Raceway      2        4
 11031  3197   364  Caskey      Toad        Sherbet Land      4        4
 11035  3198   364  Caskey      Toad     Toad's Turnpike      4        4
 11040  3200   364  Caskey     Peach       Wario Stadium      1        4
 11047  3201   364  Caskey     Yoshi       Royal Raceway      4        4
 11127  3223   365  Caskey     Luigi       Royal Raceway      3        4
 13489  3913   431  Caskey     Luigi       Royal Raceway      4        4
 13499  3916   431  Caskey     Luigi       Wario Stadium      2        4
 15327  4495   490  Caskey     Yoshi       Wario Stadium      2        4
 16248  4767   532  Caskey     Yoshi       Wario Stadium      4        4
 16256  4769   532  Caskey     Peach       Royal Raceway      4        4
 18276  5345   638  Caskey    Bowser     Bowser's Castle      4        4
 18280  5346   638  Caskey    Bowser       Royal Raceway      4        4
 19713  5744   691  Caskey      Toad        Moo Moo Farm      3        4
 19719  5746   691  Caskey     Peach       Royal Raceway      2        4
 19726  5748   691  Caskey      Toad       Wario Stadium      2        4

              DATE  SEASON
 196    2021-09-24       0
 199    2021-09-24       0
 1344   2021-10-16       0
 1349   2021-10-16       0
 1353   2021-10-16       0
 1357   2021-10-16       0
 1422   2021-10-17       0
 1426   2021-10-18       0
 1430   2021-10-18       0
 2658   2021-11-14       1
 2661   2021-11-14       1
 4661   2022-01-23       1
 4665   2022-01-23       1
 5262   2022-02-13       2
 5266   2022-02-13       2
 5268   2022-02-13       2
 5273   2022-02-13       2
 5497   2022-02-18       2
 7109   2022-04-07       3
 7113   2022-04-07       3
 7120   2022-04-07       3
 8129   2022-05-07       3
 10861  2022-08-05       5
 10865  2022-08-05       5
 11031  2022-08-11       5
 11035  2022-08-11       5
 11040  2022-08-11       5
 11047  2022-08-11       5
 11127  2022-08-12       5
 13489  2022-10-16       6
 13499  2022-10-16       6
 15327  2022-12-29       7
 16248  2023-02-12       8
 16256  2023-02-12       8
 18276  2023-06-14       9
 18280  2023-06-14       9
 19713  2024-06-01      10
 19719  2024-06-01      10
 19726  2024-06-01      10  ,
 'Duncan P':        UID  SUID      NAME CHARACTER                 MAP  PLACE  PLAYERS  \
 205     56     6  Duncan P     Luigi     Kalimari Desert      4        4
 209     57     6  Duncan P     Luigi   Banshee Boardwalk      4        4
 3525  1004    88  Duncan P     Luigi        Yoshi Valley      4        4
 3529  1005    88  Duncan P     Peach       Wario Stadium      4        4
 3533  1006    88  Duncan P     Peach        Sherbet Land      4        4
 3536  1007    88  Duncan P     Peach       Mario Raceway      3        4
 3541  1008    88  Duncan P     Peach  Koopa Troopa Beach      4        4
 3544  1009    88  Duncan P     Luigi     Frappe Snowland      3        4
 6091  1675   208  Duncan P     Peach  Koopa Troopa Beach      4        4

             DATE  SEASON
 205   2021-09-24       0
 209   2021-09-24       0
 3525  2021-12-07       1
 3529  2021-12-07       1
 3533  2021-12-07       1
 3536  2021-12-07       1
 3541  2021-12-07       1
 3544  2021-12-07       1
 6091  2022-03-04       2  ,
 'Graber':         UID  SUID    NAME CHARACTER                 MAP  PLACE  PLAYERS  \
 206      56     6  Graber      Toad     Kalimari Desert      3        4
 210      57     6  Graber      Toad   Banshee Boardwalk      2        4
 213      58     6  Graber      Toad     Bowser's Castle      1        4
 245      67     8  Graber     Peach     Toad's Turnpike      4        4
 250      68     8  Graber     Peach       Royal Raceway      4        4
 ...     ...   ...     ...       ...                 ...    ...      ...
 19838  5776   691  Graber      Toad       Royal Raceway      4        4
 20006  5821   696  Graber     Peach  Koopa Troopa Beach      4        4
 20053  5833   697  Graber     Peach   Banshee Boardwalk      2        4
 20058  5834   697  Graber     Peach        Yoshi Valley      3        4
 20062  5835   697  Graber     Peach       D.K.'s Jungle      3        4

              DATE  SEASON
 206    2021-09-24       0
 210    2021-09-24       0
 213    2021-09-24       0
 245    2021-09-27       0
 250    2021-09-27       0
 ...           ...     ...
 19838  2024-06-01      10
 20006  2024-06-06      10
 20053  2024-06-07      10
 20058  2024-06-07      10
 20062  2024-06-07      10

 [319 rows x 9 columns],
 'Anthony':         UID  SUID     NAME CHARACTER              MAP  PLACE  PLAYERS  \
 410     113    11  Anthony    Bowser     Yoshi Valley      4        4
 753     211    19  Anthony     Yoshi  Toad's Turnpike      4        4
 853     239    21  Anthony      Toad  Kalimari Desert      4        4
 1259    352    28  Anthony     Peach  Kalimari Desert      3        4
 1264    353    28  Anthony     Peach    Wario Stadium      4        4
 ...     ...   ...      ...       ...              ...    ...      ...
 18051  5282   627  Anthony      Toad    D.K.'s Jungle      3        4
 18056  5283   627  Anthony     Yoshi    Wario Stadium      4        4
 18060  5284   627  Anthony     Peach  Toad's Turnpike      4        4
 18067  5286   627  Anthony      Toad    Wario Stadium      3        4
 18071  5287   627  Anthony      Toad    Wario Stadium      3        4

              DATE  SEASON
 410    2021-09-30       0
 753    2021-10-05       0
 853    2021-10-07       0
 1259   2021-10-14       0
 1264   2021-10-14       0
 ...           ...     ...
 18051  2023-05-28       9
 18056  2023-05-28       9
 18060  2023-05-28       9
 18067  2023-05-28       9
 18071  2023-05-28       9

 [282 rows x 9 columns],
 'Garrett':         UID  SUID     NAME CHARACTER                MAP  PLACE  PLAYERS  \
 627     176    15  Garrett      Toad    Kalimari Desert      4        4
 631     177    15  Garrett      Toad      D.K.'s Jungle      4        4
 18655  5458   665  Garrett     Luigi    Toad's Turnpike      4        4

In [55]:
from itertools import combinations

c = list(combinations(f["NAME"].unique(), 2))

c

[('Cole', 'Connor'),
 ('Cole', 'Cooper'),
 ('Cole', 'Triston'),
 ('Cole', 'Blake'),
 ('Cole', 'Matt'),
 ('Cole', 'Regan'),
 ('Cole', 'Jake'),
 ('Cole', 'Chandler'),
 ('Cole', 'Luke'),
 ('Cole', 'Caskey'),
 ('Cole', 'Duncan P'),
 ('Cole', 'Graber'),
 ('Cole', 'Anthony'),
 ('Cole', 'Garrett'),
 ('Cole', 'Konnor'),
 ('Cole', 'Joey'),
 ('Cole', 'Martin'),
 ('Cole', 'Andrew'),
 ('Cole', 'Miller'),
 ('Cole', 'Kayla'),
 ('Cole', 'Chloe'),
 ('Cole', 'Ben'),
 ('Cole', 'Sam'),
 ('Cole', 'Robert'),
 ('Cole', 'Colton'),
 ('Cole', 'Mitch'),
 ('Cole', 'Justin'),
 ('Cole', 'Coop W'),
 ('Cole', 'Randy'),
 ('Cole', 'Domingo'),
 ('Cole', 'Austin'),
 ('Cole', 'Billy'),
 ('Cole', 'Mikey'),
 ('Cole', 'Hughes'),
 ('Cole', 'Kieran'),
 ('Cole', 'Kali'),
 ('Cole', 'Antonio'),
 ('Connor', 'Cooper'),
 ('Connor', 'Triston'),
 ('Connor', 'Blake'),
 ('Connor', 'Matt'),
 ('Connor', 'Regan'),
 ('Connor', 'Jake'),
 ('Connor', 'Chandler'),
 ('Connor', 'Luke'),
 ('Connor', 'Caskey'),
 ('Connor', 'Duncan P'),
 ('Connor', 'Graber'),
 ('Connor', 'Anthony'),
 ('Connor', 'Garrett'),
 ('Connor', 'Konnor'),
 ('Connor', 'Joey'),
 ('Connor', 'Martin'),
 ('Connor', 'Andrew'),
 ('Connor', 'Miller'),
 ('Connor', 'Kayla'),
 ('Connor', 'Chloe'),
 ('Connor', 'Ben'),
 ('Connor', 'Sam'),
 ('Connor', 'Robert'),
 ('Connor', 'Colton'),
 ('Connor', 'Mitch'),
 ('Connor', 'Justin'),
 ('Connor', 'Coop W'),
 ('Connor', 'Randy'),
 ('Connor', 'Domingo'),
 ('Connor', 'Austin'),
 ('Connor', 'Billy'),
 ('Connor', 'Mikey'),
 ('Connor', 'Hughes'),
 ('Connor', 'Kieran'),
 ('Connor', 'Kali'),
 ('Connor', 'Antonio'),
 ('Cooper', 'Triston'),
 ('Cooper', 'Blake'),
 ('Cooper', 'Matt'),
 ('Cooper', 'Regan'),
 ('Cooper', 'Jake'),
 ('Cooper', 'Chandler'),
 ('Cooper', 'Luke'),
 ('Cooper', 'Caskey'),
 ('Cooper', 'Duncan P'),
 ('Cooper', 'Graber'),
 ('Cooper', 'Anthony'),
 ('Cooper', 'Garrett'),
 ('Cooper', 'Konnor'),
 ('Cooper', 'Joey'),
 ('Cooper', 'Martin'),
 ('Cooper', 'Andrew'),
 ('Cooper', 'Miller'),
 ('Cooper', 'Kayla'),
 ('Cooper', 'Chloe'),
 ('Cooper', 'Ben'),
 ('Cooper', 'Sam'),
 ('Cooper', 'Robert'),
 ('Cooper', 'Colton'),
 ('Cooper', 'Mitch'),
 ('Cooper', 'Justin'),
 ('Cooper', 'Coop W'),
 ('Cooper', 'Randy'),
 ('Cooper', 'Domingo'),
 ('Cooper', 'Austin'),
 ('Cooper', 'Billy'),
 ('Cooper', 'Mikey'),
 ('Cooper', 'Hughes'),
 ('Cooper', 'Kieran'),
 ('Cooper', 'Kali'),
 ('Cooper', 'Antonio'),
 ('Triston', 'Blake'),
 ('Triston', 'Matt'),
 ('Triston', 'Regan'),
 ('Triston', 'Jake'),
 ('Triston', 'Chandler'),
 ('Triston', 'Luke'),
 ('Triston', 'Caskey'),
 ('Triston', 'Duncan P'),
 ('Triston', 'Graber'),
 ('Triston', 'Anthony'),
 ('Triston', 'Garrett'),
 ('Triston', 'Konnor'),
 ('Triston', 'Joey'),
 ('Triston', 'Martin'),
 ('Triston', 'Andrew'),
 ('Triston', 'Miller'),
 ('Triston', 'Kayla'),
 ('Triston', 'Chloe'),
 ('Triston', 'Ben'),
 ('Triston', 'Sam'),
 ('Triston', 'Robert'),
 ('Triston', 'Colton'),
 ('Triston', 'Mitch'),
 ('Triston', 'Justin'),
 ('Triston', 'Coop W'),
 ('Triston', 'Randy'),
 ('Triston', 'Domingo'),
 ('Triston', 'Austin'),
 ('Triston', 'Billy'),
 ('Triston', 'Mikey'),
 ('Triston', 'Hughes'),
 ('Triston', 'Kieran'),
 ('Triston', 'Kali'),
 ('Triston', 'Antonio'),
 ('Blake', 'Matt'),
 ('Blake', 'Regan'),
 ('Blake', 'Jake'),
 ('Blake', 'Chandler'),
 ('Blake', 'Luke'),
 ('Blake', 'Caskey'),
 ('Blake', 'Duncan P'),
 ('Blake', 'Graber'),
 ('Blake', 'Anthony'),
 ('Blake', 'Garrett'),
 ('Blake', 'Konnor'),
 ('Blake', 'Joey'),
 ('Blake', 'Martin'),
 ('Blake', 'Andrew'),
 ('Blake', 'Miller'),
 ('Blake', 'Kayla'),
 ('Blake', 'Chloe'),
 ('Blake', 'Ben'),
 ('Blake', 'Sam'),
 ('Blake', 'Robert'),
 ('Blake', 'Colton'),
 ('Blake', 'Mitch'),
 ('Blake', 'Justin'),
 ('Blake', 'Coop W'),
 ('Blake', 'Randy'),
 ('Blake', 'Domingo'),
 ('Blake', 'Austin'),
 ('Blake', 'Billy'),
 ('Blake', 'Mikey'),
 ('Blake', 'Hughes'),
 ('Blake', 'Kieran'),
 ('Blake', 'Kali'),
 ('Blake', 'Antonio'),
 ('Matt', 'Regan'),
 ('Matt', 'Jake'),
 ('Matt', 'Chandler'),
 ('Matt', 'Luke'),
 ('Matt', 'Caskey'),
 ('Matt', 'Duncan P'),
 ('Matt', 'Graber'),
 ('Matt', 'Anthony'),
 ('Matt', 'Garrett'),
 ('Matt', 'Konnor'),
 ('Matt', 'Joey'),
 ('Matt', 'Martin'),
 ('Matt', 'Andrew'),
 ('Matt', 'Miller'),
 ('Matt', 'Kayla'),
 ('Matt', 'Chloe'),
 ('Matt', 'Ben'),
 ('Matt', 'Sam'),
 ('Matt', 'Robert'),
 ('Matt', 'Colton'),
 ('Matt', 'Mitch'),
 ('Matt', 'Justin'),
 ('Matt', 'Coop W'),
 ('Matt', 'Randy'),
 ('Matt', 'Domingo'),
 ('Matt', 'Austin'),
 ('Matt', 'Billy'),
 ('Matt', 'Mikey'),
 ('Matt', 'Hughes'),
 ('Matt', 'Kieran'),
 ('Matt', 'Kali'),
 ('Matt', 'Antonio'),
 ('Regan', 'Jake'),
 ('Regan', 'Chandler'),
 ('Regan', 'Luke'),
 ('Regan', 'Caskey'),
 ('Regan', 'Duncan P'),
 ('Regan', 'Graber'),
 ('Regan', 'Anthony'),
 ('Regan', 'Garrett'),
 ('Regan', 'Konnor'),
 ('Regan', 'Joey'),
 ('Regan', 'Martin'),
 ('Regan', 'Andrew'),
 ('Regan', 'Miller'),
 ('Regan', 'Kayla'),
 ('Regan', 'Chloe'),
 ('Regan', 'Ben'),
 ('Regan', 'Sam'),
 ('Regan', 'Robert'),
 ('Regan', 'Colton'),
 ('Regan', 'Mitch'),
 ('Regan', 'Justin'),
 ('Regan', 'Coop W'),
 ('Regan', 'Randy'),
 ('Regan', 'Domingo'),
 ('Regan', 'Austin'),
 ('Regan', 'Billy'),
 ('Regan', 'Mikey'),
 ('Regan', 'Hughes'),
 ('Regan', 'Kieran'),
 ('Regan', 'Kali'),
 ('Regan', 'Antonio'),
 ('Jake', 'Chandler'),
 ('Jake', 'Luke'),
 ('Jake', 'Caskey'),
 ('Jake', 'Duncan P'),
 ('Jake', 'Graber'),
 ('Jake', 'Anthony'),
 ('Jake', 'Garrett'),
 ('Jake', 'Konnor'),
 ('Jake', 'Joey'),
 ('Jake', 'Martin'),
 ('Jake', 'Andrew'),
 ('Jake', 'Miller'),
 ('Jake', 'Kayla'),
 ('Jake', 'Chloe'),
 ('Jake', 'Ben'),
 ('Jake', 'Sam'),
 ('Jake', 'Robert'),
 ('Jake', 'Colton'),
 ('Jake', 'Mitch'),
 ('Jake', 'Justin'),
 ('Jake', 'Coop W'),
 ('Jake', 'Randy'),
 ('Jake', 'Domingo'),
 ('Jake', 'Austin'),
 ('Jake', 'Billy'),
 ('Jake', 'Mikey'),
 ('Jake', 'Hughes'),
 ('Jake', 'Kieran'),
 ('Jake', 'Kali'),
 ('Jake', 'Antonio'),
 ('Chandler', 'Luke'),
 ('Chandler', 'Caskey'),
 ('Chandler', 'Duncan P'),
 ('Chandler', 'Graber'),
 ('Chandler', 'Anthony'),
 ('Chandler', 'Garrett'),
 ('Chandler', 'Konnor'),
 ('Chandler', 'Joey'),
 ('Chandler', 'Martin'),
 ('Chandler', 'Andrew'),
 ('Chandler', 'Miller'),
 ('Chandler', 'Kayla'),
 ('Chandler', 'Chloe'),
 ('Chandler', 'Ben'),
 ('Chandler', 'Sam'),
 ('Chandler', 'Robert'),
 ('Chandler', 'Colton'),
 ('Chandler', 'Mitch'),
 ('Chandler', 'Justin'),
 ('Chandler', 'Coop W'),
 ('Chandler', 'Randy'),
 ('Chandler', 'Domingo'),
 ('Chandler', 'Austin'),
 ('Chandler', 'Billy'),
 ('Chandler', 'Mikey'),
 ('Chandler', 'Hughes'),
 ('Chandler', 'Kieran'),
 ('Chandler', 'Kali'),
 ('Chandler', 'Antonio'),
 ('Luke', 'Caskey'),
 ('Luke', 'Duncan P'),
 ('Luke', 'Graber'),
 ('Luke', 'Anthony'),
 ('Luke', 'Garrett'),
 ('Luke', 'Konnor'),
 ('Luke', 'Joey'),
 ('Luke', 'Martin'),
 ('Luke', 'Andrew'),
 ('Luke', 'Miller'),
 ('Luke', 'Kayla'),
 ('Luke', 'Chloe'),
 ('Luke', 'Ben'),
 ('Luke', 'Sam'),
 ('Luke', 'Robert'),
 ('Luke', 'Colton'),
 ('Luke', 'Mitch'),
 ('Luke', 'Justin'),
 ('Luke', 'Coop W'),
 ('Luke', 'Randy'),
 ('Luke', 'Domingo'),
 ('Luke', 'Austin'),
 ('Luke', 'Billy'),
 ('Luke', 'Mikey'),
 ('Luke', 'Hughes'),
 ('Luke', 'Kieran'),
 ('Luke', 'Kali'),
 ('Luke', 'Antonio'),
 ('Caskey', 'Duncan P'),
 ('Caskey', 'Graber'),
 ('Caskey', 'Anthony'),
 ('Caskey', 'Garrett'),
 ('Caskey', 'Konnor'),
 ('Caskey', 'Joey'),
 ('Caskey', 'Martin'),
 ('Caskey', 'Andrew'),
 ('Caskey', 'Miller'),
 ('Caskey', 'Kayla'),
 ('Caskey', 'Chloe'),
 ('Caskey', 'Ben'),
 ('Caskey', 'Sam'),
 ('Caskey', 'Robert'),
 ('Caskey', 'Colton'),
 ('Caskey', 'Mitch'),
 ('Caskey', 'Justin'),
 ('Caskey', 'Coop W'),
 ('Caskey', 'Randy'),
 ('Caskey', 'Domingo'),
 ('Caskey', 'Austin'),
 ('Caskey', 'Billy'),
 ('Caskey', 'Mikey'),
 ('Caskey', 'Hughes'),
 ('Caskey', 'Kieran'),
 ('Caskey', 'Kali'),
 ('Caskey', 'Antonio'),
 ('Duncan P', 'Graber'),
 ('Duncan P', 'Anthony'),
 ('Duncan P', 'Garrett'),
 ('Duncan P', 'Konnor'),
 ('Duncan P', 'Joey'),
 ('Duncan P', 'Martin'),
 ('Duncan P', 'Andrew'),
 ('Duncan P', 'Miller'),
 ('Duncan P', 'Kayla'),
 ('Duncan P', 'Chloe'),
 ('Duncan P', 'Ben'),
 ('Duncan P', 'Sam'),
 ('Duncan P', 'Robert'),
 ('Duncan P', 'Colton'),
 ('Duncan P', 'Mitch'),
 ('Duncan P', 'Justin'),
 ('Duncan P', 'Coop W'),
 ('Duncan P', 'Randy'),
 ('Duncan P', 'Domingo'),
 ('Duncan P', 'Austin'),
 ('Duncan P', 'Billy'),
 ('Duncan P', 'Mikey'),
 ('Duncan P', 'Hughes'),
 ('Duncan P', 'Kieran'),
 ('Duncan P', 'Kali'),
 ('Duncan P', 'Antonio'),
 ('Graber', 'Anthony'),
 ('Graber', 'Garrett'),
 ('Graber', 'Konnor'),
 ('Graber', 'Joey'),
 ('Graber', 'Martin'),
 ('Graber', 'Andrew'),
 ('Graber', 'Miller'),
 ('Graber', 'Kayla'),
 ('Graber', 'Chloe'),
 ('Graber', 'Ben'),
 ('Graber', 'Sam'),
 ('Graber', 'Robert'),
 ('Graber', 'Colton'),
 ('Graber', 'Mitch'),
 ('Graber', 'Justin'),
 ('Graber', 'Coop W'),
 ('Graber', 'Randy'),
 ('Graber', 'Domingo'),
 ('Graber', 'Austin'),
 ('Graber', 'Billy'),
 ('Graber', 'Mikey'),
 ('Graber', 'Hughes'),
 ('Graber', 'Kieran'),
 ('Graber', 'Kali'),
 ('Graber', 'Antonio'),
 ('Anthony', 'Garrett'),
 ('Anthony', 'Konnor'),
 ('Anthony', 'Joey'),
 ('Anthony', 'Martin'),
 ('Anthony', 'Andrew'),
 ('Anthony', 'Miller'),
 ('Anthony', 'Kayla'),
 ('Anthony', 'Chloe'),
 ('Anthony', 'Ben'),
 ('Anthony', 'Sam'),
 ('Anthony', 'Robert'),
 ('Anthony', 'Colton'),
 ('Anthony', 'Mitch'),
 ('Anthony', 'Justin'),
 ('Anthony', 'Coop W'),
 ('Anthony', 'Randy'),
 ('Anthony', 'Domingo'),
 ('Anthony', 'Austin'),
 ('Anthony', 'Billy'),
 ('Anthony', 'Mikey'),
 ('Anthony', 'Hughes'),
 ('Anthony', 'Kieran'),
 ('Anthony', 'Kali'),
 ('Anthony', 'Antonio'),
 ('Garrett', 'Konnor'),
 ('Garrett', 'Joey'),
 ('Garrett', 'Martin'),
 ('Garrett', 'Andrew'),
 ('Garrett', 'Miller'),
 ('Garrett', 'Kayla'),
 ('Garrett', 'Chloe'),
 ('Garrett', 'Ben'),
 ('Garrett', 'Sam'),
 ('Garrett', 'Robert'),
 ('Garrett', 'Colton'),
 ('Garrett', 'Mitch'),
 ('Garrett', 'Justin'),
 ('Garrett', 'Coop W'),
 ('Garrett', 'Randy'),
 ('Garrett', 'Domingo'),
 ('Garrett', 'Austin'),
 ('Garrett', 'Billy'),
 ('Garrett', 'Mikey'),
 ('Garrett', 'Hughes'),
 ('Garrett', 'Kieran'),
 ('Garrett', 'Kali'),
 ('Garrett', 'Antonio'),
 ('Konnor', 'Joey'),
 ('Konnor', 'Martin'),
 ('Konnor', 'Andrew'),
 ('Konnor', 'Miller'),
 ('Konnor', 'Kayla'),
 ('Konnor', 'Chloe'),
 ('Konnor', 'Ben'),
 ('Konnor', 'Sam'),
 ('Konnor', 'Robert'),
 ('Konnor', 'Colton'),
 ('Konnor', 'Mitch'),
 ('Konnor', 'Justin'),
 ('Konnor', 'Coop W'),
 ('Konnor', 'Randy'),
 ('Konnor', 'Domingo'),
 ('Konnor', 'Austin'),
 ('Konnor', 'Billy'),
 ('Konnor', 'Mikey'),
 ('Konnor', 'Hughes'),
 ('Konnor', 'Kieran'),
 ('Konnor', 'Kali'),
 ('Konnor', 'Antonio'),
 ('Joey', 'Martin'),
 ('Joey', 'Andrew'),
 ('Joey', 'Miller'),
 ('Joey', 'Kayla'),
 ('Joey', 'Chloe'),
 ('Joey', 'Ben'),
 ('Joey', 'Sam'),
 ('Joey', 'Robert'),
 ('Joey', 'Colton'),
 ('Joey', 'Mitch'),
 ('Joey', 'Justin'),
 ('Joey', 'Coop W'),
 ('Joey', 'Randy'),
 ('Joey', 'Domingo'),
 ('Joey', 'Austin'),
 ('Joey', 'Billy'),
 ('Joey', 'Mikey'),
 ('Joey', 'Hughes'),
 ('Joey', 'Kieran'),
 ('Joey', 'Kali'),
 ('Joey', 'Antonio'),
 ('Martin', 'Andrew'),
 ('Martin', 'Miller'),
 ('Martin', 'Kayla'),
 ('Martin', 'Chloe'),
 ('Martin', 'Ben'),
 ('Martin', 'Sam'),
 ('Martin', 'Robert'),
 ('Martin', 'Colton'),
 ('Martin', 'Mitch'),
 ('Martin', 'Justin'),
 ('Martin', 'Coop W'),
 ('Martin', 'Randy'),
 ('Martin', 'Domingo'),
 ('Martin', 'Austin'),
 ('Martin', 'Billy'),
 ('Martin', 'Mikey'),
 ('Martin', 'Hughes'),
 ('Martin', 'Kieran'),
 ('Martin', 'Kali'),
 ('Martin', 'Antonio'),
 ('Andrew', 'Miller'),
 ('Andrew', 'Kayla'),
 ('Andrew', 'Chloe'),
 ('Andrew', 'Ben'),
 ('Andrew', 'Sam'),
 ('Andrew', 'Robert'),
 ('Andrew', 'Colton'),
 ('Andrew', 'Mitch'),
 ('Andrew', 'Justin'),
 ('Andrew', 'Coop W'),
 ('Andrew', 'Randy'),
 ('Andrew', 'Domingo'),
 ('Andrew', 'Austin'),
 ('Andrew', 'Billy'),
 ('Andrew', 'Mikey'),
 ('Andrew', 'Hughes'),
 ('Andrew', 'Kieran'),
 ('Andrew', 'Kali'),
 ('Andrew', 'Antonio'),
 ('Miller', 'Kayla'),
 ('Miller', 'Chloe'),
 ('Miller', 'Ben'),
 ('Miller', 'Sam'),
 ('Miller', 'Robert'),
 ('Miller', 'Colton'),
 ('Miller', 'Mitch'),
 ('Miller', 'Justin'),
 ('Miller', 'Coop W'),
 ('Miller', 'Randy'),
 ('Miller', 'Domingo'),
 ('Miller', 'Austin'),
 ('Miller', 'Billy'),
 ('Miller', 'Mikey'),
 ('Miller', 'Hughes'),
 ('Miller', 'Kieran'),
 ('Miller', 'Kali'),
 ('Miller', 'Antonio'),
 ('Kayla', 'Chloe'),
 ('Kayla', 'Ben'),
 ('Kayla', 'Sam'),
 ('Kayla', 'Robert'),
 ('Kayla', 'Colton'),
 ('Kayla', 'Mitch'),
 ('Kayla', 'Justin'),
 ('Kayla', 'Coop W'),
 ('Kayla', 'Randy'),
 ('Kayla', 'Domingo'),
 ('Kayla', 'Austin'),
 ('Kayla', 'Billy'),
 ('Kayla', 'Mikey'),
 ('Kayla', 'Hughes'),
 ('Kayla', 'Kieran'),
 ('Kayla', 'Kali'),
 ('Kayla', 'Antonio'),
 ('Chloe', 'Ben'),
 ('Chloe', 'Sam'),
 ('Chloe', 'Robert'),
 ('Chloe', 'Colton'),
 ('Chloe', 'Mitch'),
 ('Chloe', 'Justin'),
 ('Chloe', 'Coop W'),
 ('Chloe', 'Randy'),
 ('Chloe', 'Domingo'),
 ('Chloe', 'Austin'),
 ('Chloe', 'Billy'),
 ('Chloe', 'Mikey'),
 ('Chloe', 'Hughes'),
 ('Chloe', 'Kieran'),
 ('Chloe', 'Kali'),
 ('Chloe', 'Antonio'),
 ('Ben', 'Sam'),
 ('Ben', 'Robert'),
 ('Ben', 'Colton'),
 ('Ben', 'Mitch'),
 ('Ben', 'Justin'),
 ('Ben', 'Coop W'),
 ('Ben', 'Randy'),
 ('Ben', 'Domingo'),
 ('Ben', 'Austin'),
 ('Ben', 'Billy'),
 ('Ben', 'Mikey'),
 ('Ben', 'Hughes'),
 ('Ben', 'Kieran'),
 ('Ben', 'Kali'),
 ('Ben', 'Antonio'),
 ('Sam', 'Robert'),
 ('Sam', 'Colton'),
 ('Sam', 'Mitch'),
 ('Sam', 'Justin'),
 ('Sam', 'Coop W'),
 ('Sam', 'Randy'),
 ('Sam', 'Domingo'),
 ('Sam', 'Austin'),
 ('Sam', 'Billy'),
 ('Sam', 'Mikey'),
 ('Sam', 'Hughes'),
 ('Sam', 'Kieran'),
 ('Sam', 'Kali'),
 ('Sam', 'Antonio'),
 ('Robert', 'Colton'),
 ('Robert', 'Mitch'),
 ('Robert', 'Justin'),
 ('Robert', 'Coop W'),
 ('Robert', 'Randy'),
 ('Robert', 'Domingo'),
 ('Robert', 'Austin'),
 ('Robert', 'Billy'),
 ('Robert', 'Mikey'),
 ('Robert', 'Hughes'),
 ('Robert', 'Kieran'),
 ('Robert', 'Kali'),
 ('Robert', 'Antonio'),
 ('Colton', 'Mitch'),
 ('Colton', 'Justin'),
 ('Colton', 'Coop W'),
 ('Colton', 'Randy'),
 ('Colton', 'Domingo'),
 ('Colton', 'Austin'),
 ('Colton', 'Billy'),
 ('Colton', 'Mikey'),
 ('Colton', 'Hughes'),
 ('Colton', 'Kieran'),
 ('Colton', 'Kali'),
 ('Colton', 'Antonio'),
 ('Mitch', 'Justin'),
 ('Mitch', 'Coop W'),
 ('Mitch', 'Randy'),
 ('Mitch', 'Domingo'),
 ('Mitch', 'Austin'),
 ('Mitch', 'Billy'),
 ('Mitch', 'Mikey'),
 ('Mitch', 'Hughes'),
 ('Mitch', 'Kieran'),
 ('Mitch', 'Kali'),
 ('Mitch', 'Antonio'),
 ('Justin', 'Coop W'),
 ('Justin', 'Randy'),
 ('Justin', 'Domingo'),
 ('Justin', 'Austin'),
 ('Justin', 'Billy'),
 ('Justin', 'Mikey'),
 ('Justin', 'Hughes'),
 ('Justin', 'Kieran'),
 ('Justin', 'Kali'),
 ('Justin', 'Antonio'),
 ('Coop W', 'Randy'),
 ('Coop W', 'Domingo'),
 ('Coop W', 'Austin'),
 ('Coop W', 'Billy'),
 ('Coop W', 'Mikey'),
 ('Coop W', 'Hughes'),
 ('Coop W', 'Kieran'),
 ('Coop W', 'Kali'),
 ('Coop W', 'Antonio'),
 ('Randy', 'Domingo'),
 ('Randy', 'Austin'),
 ('Randy', 'Billy'),
 ('Randy', 'Mikey'),
 ('Randy', 'Hughes'),
 ('Randy', 'Kieran'),
 ('Randy', 'Kali'),
 ('Randy', 'Antonio'),
 ('Domingo', 'Austin'),
 ('Domingo', 'Billy'),
 ('Domingo', 'Mikey'),
 ('Domingo', 'Hughes'),
 ('Domingo', 'Kieran'),
 ('Domingo', 'Kali'),
 ('Domingo', 'Antonio'),
 ('Austin', 'Billy'),
 ('Austin', 'Mikey'),
 ('Austin', 'Hughes'),
 ('Austin', 'Kieran'),
 ('Austin', 'Kali'),
 ('Austin', 'Antonio'),
 ('Billy', 'Mikey'),
 ('Billy', 'Hughes'),
 ('Billy', 'Kieran'),
 ('Billy', 'Kali'),
 ('Billy', 'Antonio'),
 ('Mikey', 'Hughes'),
 ('Mikey', 'Kieran'),
 ('Mikey', 'Kali'),
 ('Mikey', 'Antonio'),
 ('Hughes', 'Kieran'),
 ('Hughes', 'Kali'),
 ('Hughes', 'Antonio'),
 ('Kieran', 'Kali'),
 ('Kieran', 'Antonio'),
 ('Kali', 'Antonio')]

In [56]:
len(c)

703

In [58]:
from alive_progress import alive_it

In [59]:
pdf = panda_df.copy()

all_vs_list = []

for combo in alive_it(it=c, total=len(c), theme="classic"):

    for uid in pdf["UID"].unique():
        t = pdf[pdf["UID"] == uid]

        if (
            t["NAME"].str.contains(combo[0]).any()
            & t["NAME"].str.contains(combo[1]).any()
        ):

            all_vs_list.append(t)

[==>!                                    ] (!) 44/703 [6%] in 2:12.7 (0.33/s)

KeyboardInterrupt:

In [10]:
pdf = panda_df.copy()

vs_list = []

for uid in pdf["UID"].unique():
    temp = pdf[pdf["UID"] == uid]

    if (
        temp["NAME"].str.contains("Cooper").any()
        & temp["NAME"].str.contains("Matt").any()
    ):

        vs_list.append(temp)

In [11]:
vs_df = pd.concat(objs=vs_list)

vs_df

,UID,SUID,NAME,CHARACTER,MAP,PLACE,PLAYERS,DATE,SEASON
23,7,1,Blake,Yoshi,Banshee Boardwalk,1,4,2021-09-20,0
24,7,1,Connor,Toad,Banshee Boardwalk,4,4,2021-09-20,0
25,7,1,Cooper,Bowser,Banshee Boardwalk,3,4,2021-09-20,0
26,7,1,Matt,Peach,Banshee Boardwalk,2,4,2021-09-20,0
27,8,1,Blake,Yoshi,Toad's Turnpike,2,3,2021-09-20,0
...,...,...,...,...,...,...,...,...,...
21585,6272,733,Konnor,Toad,Wario Stadium,4,4,2024-07-13,11
21586,6273,733,Konnor,Yoshi,Frappe Snowland,1,4,2024-07-13,11
21587,6273,733,Matt,Bowser,Frappe Snowland,2,4,2024-07-13,11
21588,6273,733,Cooper,Peach,Frappe Snowland,3,4,2024-07-13,11
21589,6273,733,Triston,Toad,Frappe Snowland,4,4,2024-07-13,11

In [12]:
vs_df.head(10)

,UID,SUID,NAME,CHARACTER,MAP,PLACE,PLAYERS,DATE,SEASON
23,7,1,Blake,Yoshi,Banshee Boardwalk,1,4,2021-09-20,0
24,7,1,Connor,Toad,Banshee Boardwalk,4,4,2021-09-20,0
25,7,1,Cooper,Bowser,Banshee Boardwalk,3,4,2021-09-20,0
26,7,1,Matt,Peach,Banshee Boardwalk,2,4,2021-09-20,0
27,8,1,Blake,Yoshi,Toad's Turnpike,2,3,2021-09-20,0
28,8,1,Cooper,Bowser,Toad's Turnpike,1,3,2021-09-20,0
29,8,1,Matt,Toad,Toad's Turnpike,3,3,2021-09-20,0
30,9,1,Blake,Yoshi,D.K.'s Jungle,3,3,2021-09-20,0
31,9,1,Cooper,Wario,D.K.'s Jungle,2,3,2021-09-20,0
32,9,1,Matt,Toad,D.K.'s Jungle,1,3,2021-09-20,0

In [13]:
vs_df[vs_df["PLACE"] == 1]

,UID,SUID,NAME,CHARACTER,MAP,PLACE,PLAYERS,DATE,SEASON
23,7,1,Blake,Yoshi,Banshee Boardwalk,1,4,2021-09-20,0
28,8,1,Cooper,Bowser,Toad's Turnpike,1,3,2021-09-20,0
32,9,1,Matt,Toad,D.K.'s Jungle,1,3,2021-09-20,0
98,27,3,Cooper,Peach,Koopa Troopa Beach,1,4,2021-09-22,0
103,28,3,Matt,Toad,Royal Raceway,1,4,2021-09-22,0
...,...,...,...,...,...,...,...,...,...
21565,6266,733,Cooper,D.K.,Banshee Boardwalk,1,2,2024-07-13,11
21575,6270,733,Cooper,Luigi,Bowser's Castle,1,4,2024-07-13,11
21579,6271,733,Matt,Yoshi,Royal Raceway,1,3,2024-07-13,11
21582,6272,733,Cooper,Wario,Wario Stadium,1,4,2024-07-13,11
21586,6273,733,Konnor,Yoshi,Frappe Snowland,1,4,2024-07-13,11

In [57]:
vs_wins_gb_c = (
    vs_df[(vs_df["PLACE"] == 1) & (vs_df["NAME"] == "Cooper")]
    .groupby(["SEASON"])
    .agg(
        NAME=pd.NamedAgg(column="NAME", aggfunc="first"),
        wins=pd.NamedAgg(column="UID", aggfunc="count"),
    )
    .reset_index()
)

vs_wins_gb_c

    SEASON    NAME  wins
0        0  Cooper    30
1        1  Cooper     5
2        2  Cooper    29
3        3  Cooper    16
4        4  Cooper    29
5        5  Cooper    24
6        6  Cooper    31
7        7  Cooper    21
8        8  Cooper    42
9        9  Cooper    33
10      10  Cooper    19

In [58]:
vs_wins_gb_m = (
    vs_df[(vs_df["PLACE"] == 1) & (vs_df["NAME"] == "Matt")]
    .groupby(["SEASON"])
    .agg(
        NAME=pd.NamedAgg(column="NAME", aggfunc="first"),
        wins=pd.NamedAgg(column="UID", aggfunc="count"),
    )
    .reset_index()
)

In [63]:
vs_gb = (
    vs_df.groupby(["SEASON", "NAME"])
    .agg(
        average_place=pd.NamedAgg(column="PLACE", aggfunc="mean"),
        games_played=pd.NamedAgg(column="UID", aggfunc="count"),
    )
    .reset_index()
)

mvc_df = (
    vs_gb[vs_gb["NAME"].isin(["Cooper", "Matt"])]
    .sort_values(by=["SEASON", "average_place"], ascending=[True, True])
    .reset_index(drop=True)
)

mvc_df

    SEASON    NAME  average_place  games_played
0        0    Matt       1.817204            93
1        0  Cooper       2.139785            93
2        1    Matt       1.965517            29
3        1  Cooper       2.346154            26
4        2    Matt       1.974684            79
5        2  Cooper       2.074074            81
6        3    Matt       1.943396            53
7        3  Cooper       2.129630            54
8        4  Cooper       1.745763            59
9        4    Matt       2.050847            59
10       5    Matt       1.884058            69
11       5  Cooper       1.985507            69
12       6    Matt       2.039216           102
13       6  Cooper       2.274510           102
14       7    Matt       2.097222            72
15       7  Cooper       2.305556            72
16       8  Cooper       1.913043            92
17       8    Matt       2.108696            92
18       9  Cooper       2.044776            67
19       9    Matt       2.328358            67
20      10  Cooper       1.794872            39
21      10    Matt       2.307692            39

In [60]:
c_merge = pd.merge(
    mvc_df, vs_wins_gb_c, on=["NAME", "SEASON"], how="inner", validate="1:1"
)

c_merge

      NAME  SEASON  average_place  games_played  wins
0   Cooper       0       2.139785            93    30
1   Cooper       1       2.346154            26     5
2   Cooper       2       2.074074            81    29
3   Cooper       3       2.129630            54    16
4   Cooper       4       1.745763            59    29
5   Cooper       5       1.985507            69    24
6   Cooper       6       2.274510           102    31
7   Cooper       7       2.305556            72    21
8   Cooper       8       1.913043            92    42
9   Cooper       9       2.044776            67    33
10  Cooper      10       1.794872            39    19

In [61]:
m_merge = pd.merge(
    mvc_df, vs_wins_gb_m, on=["NAME", "SEASON"], how="inner", validate="1:1"
)

m_merge

    NAME  SEASON  average_place  games_played  wins
0   Matt       0       1.817204            93    45
1   Matt       1       1.965517            29    10
2   Matt       2       1.974684            79    33
3   Matt       3       1.943396            53    24
4   Matt       4       2.050847            59    19
5   Matt       5       1.884058            69    32
6   Matt       6       2.039216           102    40
7   Matt       7       2.097222            72    29
8   Matt       8       2.108696            92    31
9   Matt       9       2.328358            67    16
10  Matt      10       2.307692            39    11

In [62]:
cat_cat_df = (
    pd.concat(objs=[c_merge, m_merge])
    .sort_values(by=["SEASON", "average_place"], ascending=[True, True])
    .reset_index(drop=True)
)

cat_cat_df

      NAME  SEASON  average_place  games_played  wins
0     Matt       0       1.817204            93    45
1   Cooper       0       2.139785            93    30
2     Matt       1       1.965517            29    10
3   Cooper       1       2.346154            26     5
4     Matt       2       1.974684            79    33
5   Cooper       2       2.074074            81    29
6     Matt       3       1.943396            53    24
7   Cooper       3       2.129630            54    16
8   Cooper       4       1.745763            59    29
9     Matt       4       2.050847            59    19
10    Matt       5       1.884058            69    32
11  Cooper       5       1.985507            69    24
12    Matt       6       2.039216           102    40
13  Cooper       6       2.274510           102    31
14    Matt       7       2.097222            72    29
15  Cooper       7       2.305556            72    21
16  Cooper       8       1.913043            92    42
17    Matt       8       2.108696            92    31
18  Cooper       9       2.044776            67    33
19    Matt       9       2.328358            67    16
20  Cooper      10       1.794872            39    19
21    Matt      10       2.307692            39    11

# MARK

In [68]:
panda_df_c_wins = (
    panda_df[(panda_df["PLACE"] == 1) & (panda_df["NAME"] == "Cooper")]
    .groupby(["SEASON"])
    .agg(
        NAME=pd.NamedAgg(column="NAME", aggfunc="first"),
        total_wins=pd.NamedAgg(column="NAME", aggfunc="count"),
    )
    .reset_index()
)

panda_df_c_wins

    SEASON    NAME  total_wins
0        0  Cooper         188
1        1  Cooper          32
2        2  Cooper         118
3        3  Cooper          90
4        4  Cooper         138
5        5  Cooper         115
6        6  Cooper         133
7        7  Cooper         173
8        8  Cooper         195
9        9  Cooper         200
10      10  Cooper         106

In [67]:
panda_df_m_wins = (
    panda_df[(panda_df["PLACE"] == 1) & (panda_df["NAME"] == "Matt")]
    .groupby(["SEASON"])
    .agg(
        NAME=pd.NamedAgg(column="NAME", aggfunc="first"),
        total_wins=pd.NamedAgg(column="UID", aggfunc="count"),
    )
    .reset_index()
)

panda_df_m_wins

    SEASON  NAME  total_wins
0        0  Matt          98
1        1  Matt          88
2        2  Matt          62
3        3  Matt          67
4        4  Matt          45
5        5  Matt          64
6        6  Matt          69
7        7  Matt          47
8        8  Matt          60
9        9  Matt          23
10      10  Matt          11